spring.application.name=demo
server.port=8081
#Each time we run framework, it will generate its own development password.
#To make a one time hit. we use this below lines of code.
#it will create a different sessId on each run, but never changes it user credentials.
spring.security.user.name=rakshi
spring.security.user.password =Java

spring.datasource.url=jdbc:postgresql://localhost:5432/rakshithdb
spring.datasource.username=postgres
spring.datasource.password=rakshith